"$schema" = 'https://starship.rs/config-schema.json'

format = """
jwfeng-MBP: \
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 0
fish_style_pwd_dir_length = 0

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

# [git_branch]
# format = "[$branch]($style)"
# style = "bright-black"

# [git_status]
# format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
# style = "cyan"
# conflicted = "​"
# untracked = "​"
# modified = "​"
# staged = "​"
# renamed = "​"
# deleted = "​"
# stashed = "≡"

# [git_branch]
# symbol = ""
# style = "bg:yellow"
# format = '[[ $symbol $branch ](fg:crust bg:yellow)]($style)'
#
# [git_status]
# style = "bg:yellow"
# format = '[[($all_status$ahead_behind )](fg:crust bg:yellow)]($style)'
# use_git_executable = true
#
[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []
